WITH tpl(key, name, beschreibung, betreff_du, betreff_sie, body_du, body_sie, platzhalter) AS (VALUES
  ('entwurf_neue_runde', 'Entwürfe — Folgerunde (Runde N)', 'An den Kunden: überarbeitete Entwürfe nach Feedback (POST /jobs/:id/export/email, Variante neue_runde). {{runde}} = Rundennummer. Body = Intro-Satz vor dem KI-Anschreiben. Hinweis: der Intro war im Code nur in Du-Form — die Sie-Fassung ist als Startwert identisch und kann hier angepasst werden.', 'Deine überarbeiteten Entwürfe — Runde {{runde}}', 'Ihre überarbeiteten Entwürfe — Runde {{runde}}', 'Danke für dein Feedback! Wir haben die Entwürfe überarbeitet — schau sie dir an:', 'Danke für dein Feedback! Wir haben die Entwürfe überarbeitet — schau sie dir an:', '["runde","stelle"]'::jsonb),
  ('entwurf_resend', 'Entwürfe — erneut gesendet', 'An den Kunden: dieselben Entwürfe nochmal (POST /jobs/:id/export/email, Variante resend). Betreff wie Erstversand; Body = kurzer Intro-Satz. Startwert der Sie-Fassung ist identisch zur Du-Fassung (im Code Du-only) und kann hier angepasst werden.', 'Deine Entwürfe sind fertig 🎨', 'Ihre Entwürfe sind fertig 🎨', 'Hier nochmal deine Entwürfe:', 'Hier nochmal deine Entwürfe:', '["runde","stelle"]'::jsonb),
  ('upload_anfrage_logo', 'Fotos & Logo — Anfrage (nur Logo)', 'An den Kunden: nur das Logo hochladen (POST /kunden/:id/anfrage, umfang=logo). customText überschreibt den Body.', 'Wir brauchen noch euer Logo für die Kampagne', 'Wir brauchen noch Ihr Logo für die Kampagne', 'wir bereiten gerade eure Recruiting-Kampagne vor und brauchen dafür noch euer Logo. Über den unten stehenden Link könnt ihr es ganz einfach hochladen.', 'wir bereiten gerade Ihre Recruiting-Kampagne vor und brauchen dafür noch Ihr Logo. Über den unten stehenden Link können Sie es ganz einfach hochladen.', '[]'::jsonb),
  ('upload_anfrage_fotos', 'Fotos & Logo — Anfrage (nur Fotos)', 'An den Kunden: nur Fotos hochladen (POST /kunden/:id/anfrage, umfang=fotos). customText überschreibt den Body.', 'Wir brauchen noch ein paar Fotos für eure Kampagne', 'Wir brauchen noch ein paar Fotos für Ihre Kampagne', 'wir bereiten gerade eure Recruiting-Kampagne vor und brauchen dafür noch ein paar Fotos vom Team / Arbeitsplatz. Über den unten stehenden Link könnt ihr sie ganz einfach hochladen.', 'wir bereiten gerade Ihre Recruiting-Kampagne vor und brauchen dafür noch ein paar Fotos vom Team / Arbeitsplatz. Über den unten stehenden Link können Sie sie ganz einfach hochladen.', '[]'::jsonb),
  ('formular_einladung_neukunden', 'Briefing-Formular-Einladung (Neukundengewinnung)', 'An den Kunden: Briefing-Formular für Neukunden-Projekte (projekttyp=neukundengewinnung). customText überschreibt den Body. Aufzählung + Tipp bleiben im Code.', 'Kurzes Briefing-Formular für eure Neukunden-Kampagne', 'Kurzes Briefing-Formular für Ihre Neukunden-Kampagne', 'wir freuen uns auf eure Neukunden-Kampagne! Damit wir starten können, haben wir ein kurzes Briefing-Formular für euch vorbereitet — dort tragt ihr alles rund um euer Angebot, eure Zielgruppe und euer Unternehmen ein. Dauert etwa 10 Minuten.', 'wir freuen uns auf Ihre Neukunden-Kampagne! Damit wir starten können, haben wir ein kurzes Briefing-Formular für Sie vorbereitet — dort tragen Sie alles rund um Ihr Angebot, Ihre Zielgruppe und Ihr Unternehmen ein. Dauert etwa 10 Minuten.', '[]'::jsonb),
  ('termin_jour_fixe', 'Termin — Jour Fixe (Betreff)', 'Betreff der Termin-Einladung „Jour Fixe" (termine.js). Der Body wird im Modal frei getippt (customText).', 'Kurzer Jour Fixe? 📅', 'Kurzer Jour Fixe? 📅', NULL, NULL, '[]'::jsonb),
  ('termin_onboarding_abgeschlossen', 'Termin — Onboarding-Abschluss (Betreff)', 'Betreff der Termin-Einladung „Onboarding-Abschluss" (termine.js). Body = customText.', 'Onboarding-Abschluss — kurzer Termin 📅', 'Onboarding-Abschluss — kurzer Termin 📅', NULL, NULL, '[]'::jsonb),
  ('termin_entwuerfe', 'Termin — Entwürfe besprechen (Betreff)', 'Betreff der Termin-Einladung „Entwürfe besprechen" (termine.js). Body = customText.', 'Lass uns deine Entwürfe besprechen 📅', 'Lass uns deine Entwürfe besprechen 📅', NULL, NULL, '[]'::jsonb),
  ('termin_go_live', 'Termin — Go-Live (Betreff)', 'Betreff der Termin-Einladung „Go-Live" (termine.js). Body = customText.', 'Dein Go-Live Termin 🚀', 'Dein Go-Live Termin 🚀', NULL, NULL, '[]'::jsonb),
  ('termin_meta_einrichtung', 'Termin — Meta-Einrichtung (Betreff)', 'Betreff der Termin-Einladung „Meta-Einrichtung" (termine.js). Body = customText.', 'Termin Meta-Einrichtung 📅', 'Termin Meta-Einrichtung 📅', NULL, NULL, '[]'::jsonb),
  ('zahlung_paypal', 'PayPal-Zahlungslink (Betreff)', 'An den Kunden: Werbebudget-Rechnung mit PayPal-Zahlungslink (POST /zahlungen/:id/send). Nur der Betreff ist editierbar; Betrag/Tabelle/Button entstehen im Code.', 'Rechnung Werbebudget — {{stelle}}', 'Rechnung Werbebudget — {{stelle}}', NULL, NULL, '["stelle"]'::jsonb),
  ('rechnung_pdf_paypal', 'PayPal-Rechnung (PDF-Anhang)', 'An den Kunden: Rechnung als PDF nach Zahlung (POST /zahlungen/:id/rechnung/send).', 'Rechnung {{rechnungsnr}} — {{firma}}', 'Rechnung {{rechnungsnr}} — {{firma}}', 'Vielen Dank für eure Zahlung! Anbei erhaltet ihr eure Rechnung als PDF im Anhang.', 'Vielen Dank für Ihre Zahlung! Anbei erhalten Sie Ihre Rechnung als PDF im Anhang.', '["rechnungsnr","firma"]'::jsonb),
  ('bewerber_benachrichtigung', 'Neue Bewerbung — Benachrichtigung (Betreff)', 'An den Kunden: neue Bewerbung eingegangen (Perspective-/Funnel-Webhook). Nur der Betreff ist editierbar; Kontakt-/Antwort-Tabelle entsteht im Code.', 'Neue Bewerbung für {{stelle}}{{name_suffix}}', 'Neue Bewerbung für {{stelle}}{{name_suffix}}', NULL, NULL, '["stelle","name_suffix"]'::jsonb),
  ('anfrage_lead', 'Neue Anfrage/Lead — Benachrichtigung (Betreff)', 'An den Kunden: neue Anfrage über die Landingpage (POST /webhooks/leads). Nur der Betreff ist editierbar; Daten-Tabelle entsteht im Code.', '🎉 Neue Anfrage für {{produkt}}: {{name}}', '🎉 Neue Anfrage für {{produkt}}: {{name}}', NULL, NULL, '["produkt","name"]'::jsonb)
)
INSERT INTO talentone_email_templates (key, agentur, name, beschreibung, betreff_du, betreff_sie, body_du, body_sie, platzhalter, updated_by)
SELECT t.key, a.agentur, t.name, t.beschreibung, t.betreff_du, t.betreff_sie, t.body_du, t.body_sie, t.platzhalter, 'seed:063'
FROM tpl t CROSS JOIN (VALUES ('talentone'), ('nowagwirth')) AS a(agentur)
ON CONFLICT (key, agentur) DO NOTHING;

UPDATE talentone_email_templates SET name='Kampagnen-Update (Update N)', beschreibung='An den Kunden: neue Werbeanzeigen während der Live-Phase (POST /jobs/:id/export/kampagne-update). {{runde}} = Update-Nummer. Der Body ist der Intro-Satz vor dem KI-Anschreiben.', betreff_du='Neue Werbeanzeigen für deine Kampagne — Update {{runde}} 📬', betreff_sie='Neue Werbeanzeigen für Ihre Kampagne — Update {{runde}} 📬', body_du='wir haben neue Werbeanzeigen für deine Kampagne erstellt, um die Performance weiter zu verbessern. Schau sie dir an und gib sie frei, damit wir sie live schalten können:', body_sie='wir haben neue Werbeanzeigen für Ihre Kampagne erstellt, um die Performance weiter zu verbessern. Sehen Sie sie sich an und geben Sie sie frei, damit wir sie live schalten können:', platzhalter='["runde","stelle"]'::jsonb WHERE key='kampagne_update' AND body_du IS NULL;