INSERT INTO public.talentone_offer_products
  (brand, category, sku, title, description, unit_price, is_default, sort_order, active)
VALUES
  ('talentone', 'setup', 'TO-SETUP-ONBOARDING',
   'Onboarding & Potenzialanalyse',
   'Strukturierter Onboarding-Prozess über das TalentOne-Portal: Erfassung Ihrer Stellenanforderungen, Arbeitgebervorteile und Unternehmens-Eckdaten. Vorabanalyse Ihrer aktuellen Online-Außenwirkung als Arbeitgeber. Zugang zum TalentOne-Kundenportal mit Bewerber-Übersicht, Kampagnen-Status und direktem Draht zu Ihrem Ansprechpartner.',
   490.00, true, 10, true),
  ('talentone', 'setup', 'TO-SETUP-CREATIVES',
   'Authentische Werbemittel mit KI-Veredelung',
   'Sie liefern uns einfache Handyfotos aus Ihrem Betriebsalltag — Ihr Team, Ihre Werkstatt, Ihre Räume. Unsere KI-gestützte Bildveredelung macht daraus hochwertige, professionelle Werbemittel: optimierte Bildqualität, stimmige Farbwelten, kampagnenfertige Formate für alle Werbeplätze. Ihr Betrieb wird mit echten Gesichtern und echten Einblicken beworben — authentisch wie ein Blick hinter die Kulissen, professionell wie eine Agenturproduktion. Kein Fototermin, kein Aufwand, keine austauschbaren Stockfotos.',
   500.00, true, 20, true),
  ('talentone', 'monthly', 'TO-MONTHLY-CAMPAIGN',
   'Kampagnen-Ausstrahlung & Bewerbermanagement',
   'Aussteuerung Ihrer Kampagne auf Facebook und Instagram sowie über 240 weiteren Werbeplätzen. Tägliche Betreuung und Optimierung, laufender Test neuer Werbetexte und Werbemittel, kontinuierliche Messung der Ergebnisse. Alle eingehenden Bewerbungen laufen strukturiert in Ihrem TalentOne-Portal zusammen. Die Ausstrahlung erfolgt über das TalentOne-Werbekonto — Sie benötigen kein eigenes Meta-Konto und keine Kreditkarte bei Meta. Eine aktive Stellenkampagne inklusive.',
   1490.00, true, 30, true),
  ('talentone', 'option_monthly', 'TO-OPT-PREQUALIFY',
   'Telefonische Vorqualifizierung der Bewerber',
   'Telefonische Vorqualifizierung aller eingehenden Bewerber durch unser Team, nach Kriterien wie Ausbildung, Wechselmotivation, Erreichbarkeit, Erfahrung und Gehaltsvorstellung. Sie sprechen nur noch mit Kandidaten, die fachlich passen und wirklich wechseln wollen.',
   490.00, false, 40, true),
  ('talentone', 'option_monthly', 'TO-OPT-EXTRA-JOB',
   'Weitere parallele Stellenkampagne',
   'Erstellung und Ausstrahlung einer zusätzlichen Stellenkampagne inklusive eigener Werbemittel, eigenem Bewerbungsprozess und separater Auswertung im Portal.',
   490.00, false, 50, true),
  ('nowag_wirth', 'setup', 'NW-SETUP-ANALYSIS',
   'Ist-Analyse & Einrichtung Onboarding-Portal',
   'Potenzialanalyse und Vorabanalyse Ihrer aktuellen Online-Außenwirkung als Arbeitgeber. Einrichtung und Zugang zum Login-Portal für Partnerbetriebe mit Zugriff auf Onboarding- und Infobereich, Bewerber-Hub, Datenaustausch, Terminbuchungen und Übersicht aller relevanten Ansprechpartner. Einrichtung einer WhatsApp-Gruppe zum täglichen Austausch mit Ihrem persönlichen Partnermanager, Ihrem Recruiter und der Geschäftsführung von Nowag & Wirth.',
   400.00, true, 10, true),
  ('nowag_wirth', 'setup', 'NW-SETUP-KICKOFF',
   'Kick-Off & Onboarding',
   'Persönlicher Onboarding-Call mit Ihrem Partnermanager zur ausführlichen Ist-Analyse, Ausarbeitung Ihrer Unternehmens-Werte und Arbeitgebervorteile sowie Einführung in das Partnerportal und den Ablauf der Zusammenarbeit.',
   300.00, true, 20, true),
  ('nowag_wirth', 'setup', 'NW-SETUP-CREATIVES',
   'Authentische Werbemittel mit KI-Veredelung',
   'Sie liefern uns einfache Handyfotos aus Ihrem Betriebsalltag — Ihr Team, Ihre Werkstatt, Ihre Räume. Unsere KI-gestützte Bildveredelung macht daraus hochwertige, professionelle Werbemittel: optimierte Bildqualität, stimmige Farbwelten, kampagnenfertige Formate für alle Werbeplätze. Ihr Betrieb wird mit echten Gesichtern und echten Einblicken beworben — authentisch wie ein Blick hinter die Kulissen, professionell wie eine Agenturproduktion. Kein Fototermin, kein Aufwand, keine austauschbaren Stockfotos.',
   600.00, true, 30, true),
  ('nowag_wirth', 'setup', 'NW-SETUP-TECH',
   'Technik-Setup auf Ihrem eigenen Werbekonto',
   'Einrichtung Ihrer kompletten Recruiting-Infrastruktur auf Ihrem eigenen Meta-Werbekonto: interaktiver Bewerbungsprozess, individuelle Qualifikationswebseite, Werbemittel-Kreation auf Basis Ihres Bildmaterials, psychologisch aufgebaute Werbetexte, Einrichtung der Kampagnen inklusive Pixel und Zielgruppen. Werbekonto, Pixel, Zielgruppendaten und sämtliche Werbemittel gehören Ihnen — Sie bauen ein eigenes, dauerhaftes Recruiting-Asset auf, das langfristig für Ihre Arbeitgebermarke arbeitet.',
   1600.00, true, 40, true),
  ('nowag_wirth', 'monthly', 'NW-MONTHLY-CAMPAIGN',
   'Kampagnen-Betreuung, Bewerbermanagement & Vorqualifizierung',
   'Betreuung der Kampagnen auf täglicher Basis mit der NOWI® Methode, Optimierung der Strategie, Test neuer Werbetexte, kontinuierliche Messung. Telefonische Vorqualifizierung aller eingehenden Bewerber nach Kriterien wie Ausbildung, Wechselmotivation, Erreichbarkeit und Gehaltsvorstellung — dokumentiert im Bewerber-Hub. 5 Tage pro Woche Unterstützung durch Ihren persönlichen Partnermanager, WhatsApp-Gruppe, wöchentliche Video-Konferenzen zur Optimierung Ihrer internen Rekrutierungsprozesse. Eine aktive Stellenkampagne inklusive.',
   1990.00, true, 50, true),
  ('nowag_wirth', 'option_setup', 'NW-OPT-PHOTO',
   'Fotopaket: Professioneller Fototag vor Ort',
   'Fototag in Ihrem Betrieb mit Profi-Fotograf: Gruppenbilder Ihres Teams, Aufnahmen aus dem Arbeitsalltag und Bilder der Geschäftsführung. Alle Bilder gehen in Ihr Eigentum über und dürfen unbegrenzt für eigene Werbezwecke weiterverwendet werden.',
   690.00, false, 60, true),
  ('nowag_wirth', 'option_monthly', 'NW-OPT-EXTRA-JOB',
   'Weitere parallele Stellenkampagne',
   'Erstellung und Ausstrahlung einer zusätzlichen Stellenkampagne inklusive eigener Werbemittel, eigenem Bewerbungsprozess und separater Auswertung im Portal.',
   690.00, false, 70, true)
ON CONFLICT (sku) DO NOTHING;

INSERT INTO public.talentone_offer_templates (brand, key, text)
VALUES
  ('talentone', 'guarantee',
   'Unsere Bewerbungsgarantie: Erhalten Sie innerhalb der ersten 30 Tage Kampagnenlaufzeit weniger als [X] qualifizierte Bewerbungen, verlängern wir die Kampagnenbetreuung ohne weitere Servicegebühr um bis zu 30 weitere Tage. Das Werbebudget läuft in diesem Zeitraum regulär weiter.'),
  ('talentone', 'payment_terms',
   'Die Servicepauschale ist 7 Tage nach Rechnungsstellung fällig. Das Werbebudget wird monatlich im Voraus berechnet; der Kampagnenstart erfolgt nach Zahlungseingang. Die monatliche Zusammenarbeit ist jederzeit zum Monatsende kündbar.'),
  ('talentone', 'reminder_email',
   E'Sehr geehrte Damen und Herren,\n\nwir möchten Sie freundlich daran erinnern, dass die Rechnung [RECHNUNGSNUMMER] über [BETRAG] vom [RECHNUNGSDATUM] bislang noch offen ist. Fälligkeitsdatum war der [FAELLIGKEIT].\n\nDamit Ihre Kampagne ohne Unterbrechung weiterlaufen kann, bitten wir Sie um kurzfristige Begleichung des offenen Betrags. Bequem per PayPal-Link in der Rechnung oder per Überweisung.\n\nSollten Sie die Zahlung bereits veranlasst haben, betrachten Sie diese Nachricht bitte als gegenstandslos.\n\nBei Fragen erreichen Sie uns jederzeit unter info@nowagwirth.de.\n\nHerzliche Grüße\nIhr TalentOne-Team'),
  ('nowag_wirth', 'guarantee',
   'Rundum-sorglos-Kampagne mit Erfolgsgarantie: Falls nach 30 Tagen Kampagnenlaufzeit noch keine Einstellung erfolgt ist, arbeitet Nowag & Wirth ohne weitere Servicegebühr weiter, bis die Einstellung erfolgreich abgeschlossen ist. Das Werbebudget läuft in diesem Zeitraum regulär weiter. Die Erfolgsgarantie setzt eine partnerschaftliche Mitwirkung voraus: Kontaktaufnahme mit vermittelten Bewerbern innerhalb von 48 Stunden, kurze Rückmeldung an Ihren Partnermanager nach jedem geführten Gespräch sowie marktübliche Konditionen für die ausgeschriebene Stelle. So stellen wir gemeinsam sicher, dass qualifizierte Bewerber nicht zwischenzeitlich anderweitig unterschreiben.'),
  ('nowag_wirth', 'payment_terms',
   'Die Zahlung ist 7 Tage nach Rechnungsstellung fällig. Die Mindestlaufzeit der monatlichen Zusammenarbeit beträgt 3 Monate, danach monatlich kündbar. Die Aussteuerung der Kampagnen erfolgt über Ihr eigenes Meta-Werbekonto; das Werbebudget entrichten Sie unmittelbar an den Werbeplattformbetreiber (Empfehlung: täglich 20–40 € pro Stelle).'),
  ('nowag_wirth', 'reminder_email',
   E'Sehr geehrte Damen und Herren,\n\nwir möchten Sie freundlich daran erinnern, dass die Rechnung [RECHNUNGSNUMMER] über [BETRAG] vom [RECHNUNGSDATUM] bislang noch offen ist. Fälligkeitsdatum war der [FAELLIGKEIT].\n\nFür einen unterbrechungsfreien Ablauf der Zusammenarbeit bitten wir Sie um kurzfristige Begleichung des offenen Betrags. Bequem per PayPal-Link in der Rechnung oder per Überweisung.\n\nSollten Sie die Zahlung bereits veranlasst haben, betrachten Sie diese Nachricht bitte als gegenstandslos.\n\nBei Fragen erreichen Sie uns jederzeit unter info@nowagwirth.de.\n\nMit den besten Grüßen\nIhr Nowag & Wirth-Team')
ON CONFLICT (brand, key) DO NOTHING;
